name: Single environment Acquia deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        default: 'dev'
        required: true
      sites:
        description: 'Select one or more sites to deploy'
        required: true
        type: choice
        options:
          - default
          - amplify
          - fsig
          - germany
          - india
          - receivership
        default: default
      run_cr:
        description: 'Run Drush CR (Cache Rebuild)'
        required: false
        default: true
        type: boolean
      run_updb:
        description: 'Run Drush UPDB (Update Database)'
        required: false
        default: false
        type: boolean
jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show selected sites
        run: |
          echo "Selected sites: ${{ inputs.sites }}"
          IFS=',' read -ra SITE_LIST <<< "${{ inputs.sites }}"
          for site in "${SITE_LIST[@]}"; do
            echo "Processing site: $site"
          done
