name: Single environment Acquia deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        default: 'dev'
        required: true
      site-default:
        description: 'Deploy main site'
        required: false
        default: true
        type: boolean
      site-amplify:
        description: 'Deploy Amplify site'
        required: false
        default: false
        type: boolean
      site-fsig:
        description: 'Deploy FSIG site'
        required: false
        default: false
        type: boolean
      site-germany:
        description: 'Deploy Germany site'
        required: false
        default: false
        type: boolean
      site-india:
        description: 'Deploy India site'
        required: false
        default: true
        type: boolean
      site-receivership:
        description: 'Deploy Receivership site'
        required: false
        default: false
        type: boolean  
      run_cr:
        description: 'Run Drush CR (Cache Rebuild)'
        required: false
        default: true
        type: boolean
      run_updb:
        description: 'Run Drush UPDB (Update Database)'
        required: false
        default: false
        type: boolean
jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show selected sites
        run: |
          echo "Branch: ${{ inputs.branch }}"
          echo "Deploy main site?: ${{ inputs.site-default }}"
          echo "Deploy Amplify site?: ${{ inputs.site-amplify }}"
          echo "Deploy Fsig site?: ${{ inputs.site-fsig }}"
          echo "Deploy Germany site?: ${{ inputs.site-germany }}"
          echo "Deploy India site?: ${{ inputs.site-india }}"
          echo "Deploy Receivership0 site?: ${{ inputs.site-receivership }}"
          echo "Run CR?: ${{ inputs.run_cr }}"
          echo "Run UPDB?: ${{ inputs.run_updb }}"
          
          
          
